/**
 * BusinessRules placeholder.
 * Phase 0 ships only IDs — actual values/guards land in Phases 2 – 5
 * as the corresponding modules come online. See SRS_Document.md §5.
 */
export const BusinessRules = {
  BL_01_NO_OVERLAPPING_LEASES: "BL-01",
  BL_02_LEASE_RENT_IMMUTABLE: "BL-02",
  BL_03_RENT_EDIT_GATE: "BL-03",
  BL_04_UNIT_STATE_GUARD: "BL-04",
  BL_05_RETIRED_UNIT_TERMINAL: "BL-05",
  BL_06_LISTED_RENT_LIVE: "BL-06",
  BL_07_CO_TENANT_APPROVAL: "BL-07",
  BL_08_TERMINATION_REQUIRES_APPROVALS: "BL-08",
  BL_09_TERMINATION_NO_AUTO_TIMEOUT: "BL-09",
  BL_10_PAYMENT_RECORDED_BY_PM: "BL-10",
  BL_11_CONCURRENT_PAYMENT_RECONCILIATION: "BL-11",
  BL_12_OVERDUE_FLIP: "BL-12",
  BL_13_LATE_FEE_ACCRUAL: "BL-13",
  BL_14_DESCRIPTION_MIN_LENGTH: "BL-14",
  BL_15_CLOSED_REQUEST_IMMUTABLE: "BL-15",
  BL_16_MAINTENANCE_CANT_RAISE: "BL-16",
  BL_17_FIVE_REQUEST_ALERT: "BL-17",
  BL_18_TENANT_TURNOVER_GAP: "BL-18",
  BL_19_PM_PROPERTY_EXCLUSIVE: "BL-19",
  BL_20_PM_TRANSFER_LOG: "BL-20",
  BL_21_TENANT_CLOSES_REQUEST: "BL-21",
  BL_22_TIMEZONE_IST: "BL-22",
  BL_23_DATE_FORMAT_DDMMYYYY: "BL-23",
} as const;

export type BusinessRuleId = (typeof BusinessRules)[keyof typeof BusinessRules];
